Cargo.toml, examples/simple_grep.rs, src/captures.rs, src/lib.rs, src/tree.rs
I added new arguments to methods `search_with_options` and `match_with_options`:
- `at` for `match_with_options`
- `from` and `to` for `search_with_options`
Rationale:
- Sometimes it is necessary to search inside subrange of passed string and get the **absolute** indices of the matches. For example, if you want to find **all** matches of some pattern in a string, you should be able to start search from some position, but get matching indices from the start of base string.
- It makes possible to perform backward search.
=> Change signature of search_with_options and match_with_options methods

src/flags.rs
`ONIG_OPTION_CAPTURE_GROUP` and `ONIG_OPTION_DONT_CAPTURE_GROUP` are actually flags for onig_new and hence should be regex options and not search options. Previously it was impossible to enable named captures and if you used those search flags it probably activated some other option, or did nothing. See: https://github.com/kkos/oniguruma/blob/master/doc/API
I discovered this because I currently have no way to get regexes involving named captures to compile.
If you want me to maintain the `SEARCH_OPTION_CAPTURE_GROUP` and its negation for backwards compatibility I can do that. But I think removing them will be fine since they don't do anything, if you were to try and use them for their intended purpose you would run into this bug compiling your regexes, and no code on Github or anywhere …
=> Fix classification of ONIG_OPTION_CAPTURE_GROUP

src/lib.rs, src/region.rs
Implements Clone for region using the existing `onig_region_copy` function from `onig_sys`. I need this for my [syntect](https://github.com/trishume/syntect) project so that I can allow users to clone parser states so that they can cache them and not re-highlight entire files when one character changes.
@iwillspeak @defuz
=> Add Clone impl for Region

.travis.yml, Cargo.toml, src/find.rs, src/lib.rs, src/pattern.rs
This allows the `onig::Regex` to be used with the `std::str::pattern`
API. `Pattern`s can be used to find a list of matches within a string,
to find prefixes, to check the existence of a substring and to trim
strings.
This implementation is probably a bit rough around the edges. I'd have
liked to have used the existing `RegexMatchs` iterator but couldn't due
to the ownership requirements of the `Pattern` trait.
Still TODO:
switch.
completes #13
=> Pattern Implementation

src/buffers.rs, src/lib.rs
Intorduce a new trait to represent a buffer of bytes with an
encoding. Using this trait define a new set of constructors for `Regex`
which are encoding aware.
Fixes #23
=> Add Encoding Support to Regex new - Incomplete

Cargo.toml
Add a target overide for `musl` environments to always enable static linking of libonig.
Fixes #31
=> Always Statically Link `onig_sys` on `musl`

onig_sys/build.rs
These environment variables are now set by rust (rust-lang/cargo#1744). This interferes with the NMAKE command on MSVC.
Fixes: #40
=> Ignore MFLAGS and MAKEFILAGS on Windows MSVC

Cargo.toml, onig_sys/Cargo.toml, src/utils.rs
https://github.com/kkos/oniguruma/blob/master/HISTORY
> 2017/08/03: Version 6.5.0
>
> 2017/07/30: [new] support Absent clear (Absent functions)
2017/07/25: abolish configure option: --enable-combination-explosion-check
2017/07/23: [new] support Absent functions (?~...)
2017/07/14: fix #65: SIZEOF_SIZE_T doesn't exist on certain architecutres
2017/07/11: [new] support \O (true anychar)
2017/07/10: [new] support \K (keep)
2017/07/10: add new node type: NODE_GIMMICK
2017/07/07: [new] support \N (no newline)
2017/07/05: [new] support \R (general newline)
2017/07/05: [new] support if-then-else syntax
2017/07/04: [new] support backref validity checker
=> Upgrade oniguruma to 6.5.0

onig_sys/Makefile.windows, onig_sys/build.rs, onig_sys/make_win32.bat, onig_sys/make_win64.bat
This is a copy of the existing Oniguruma `Makefile.windows`
which includes support for building the object files and
lilbraries in a differnet directory. Copies of the make
batch files then set the approrpiate variables so that objects
are placed in the current directory when compiled.
Part of #49
=> Add MSVC Makefile for Out-of-Tree Build

onig_sys/build.rs
All link types can now be overriden with the appropriate environment
vairable too. This should make the defualt use case on Windows (to
statically link) easier.
Fixes #51
=> Add `LinkType` to Build Script & Default to Static on MSVC

examples/dollar.rs
This addresses an issue raised in #59. The example shows _one way_ of
impelementing 'dollar replacement' patterns. This allows the use of
numbered capture groups in the replacement text without having to
resort to using a closure.
=> Add an Example of Implementing Dollar Replacement Strings

README.md, onig_sys/build.rs
If the library can't be found by `pkg-config` then statically link by
default. This adds a new environment variable
`RUSTONIG_DYNAMIC_LIBONIG` which enables dynamic linking. Linking is
therefore defined by:
* If `RUSTONIG_DYNAMIC_LIBONIG` is set:
* Dynamic if true
* Static if false
* If `RUSTONIG_STATIC_LIBONIG` is set:
* Static if true
* Dynamic if false
* If neither is set, then static linking is used.
Part of #65. Fixes #63.
=> Switch to Statically Linking by Default

Cargo.toml, README.md, onig_sys/Cargo.toml, onig_sys/build.rs
For #72. Split into two commits:
* Allow to disable using system libonig via RUSTONIG_SYSTEM_LIBONIG=0
* Add print-debug feature for debugging Oniguruma
Note that I've only tested this on Mac. Windows uses a different build system, so I'm not sure how to add it there.
=> Feature for debugging Oniguruma parsing/compiling/matching

onig_sys/src/lib.rs, src/lib.rs, src/match_param.rs
They use the new `onig_match_with_param` and `onig_search_with_param` in
Oniguruma.
Note that `onig_match` in Oniguruma delegates to
`onig_match_with_param`, so we can do the same for `Regex`.
Part of #75. (Based on #78, otherwise they would have conflicted.)
=> Add `match_with_param` and `search_with_param` to `Regex`

Cargo.toml, onig_sys/Cargo.toml, onig_sys/build.rs, onig_sys/src/constants.rs, onig_sys/src/lib.rs, onig_sys/src/onigenc.rs, src/lib.rs, src/match_param.rs, src/tree.rs, src/utils.rs
Updates to support the full 6.8 Oniguruma API.
Oniguruma 6.8.0 adds new API surface for passing parameters into the search and match functions. This PR exposes the parameters object in both the `onig_sys` and `onig` crates & adds support for setting some of those match parameters.
Not sure what other more ergonomic APIs we might choose to expose built on top of these yet.
Fixes #75
=> Six dot eight

onig_sys/build.rs
Otherwise compilation fails because of missing symbols:
```
= note: Undefined symbols for architecture x86_64:
"_onig_initialize_match_param", referenced from:
_$LT$onig..match_param..MatchParam$u20$as$u20$core..default..Default$GT$::default::hc994870608029158 in onig-125d7067550179ab.45igp2irmro0fuey.rcgu.o
"_onig_free_match_param", referenced from:
_$LT$onig..match_param..MatchParam$u20$as$u20$core..ops..drop..Drop$GT$::drop::h3a08a19b3e6bde67 in onig-125d7067550179ab.45igp2irmro0fuey.rcgu.o
"_onig_new_match_param", referenced from:
_$LT$onig..match_param..MatchParam$u20$as$u20$core..default..Default$GT$::default::hc994870608029158 in onig-125d7067550179ab.45igp2irmro0fuey.rcgu.o
"_onig_set_match_stack_limit_size_of_match_param", referenced from: …
```
=> Only use system oniguruma if it's at least version 6.8.0

appveyor.yml
It looks like -gnu targets won't work until this is fixed: 
https://github.com/rust-lang/rust/issues/47048
#82
=> Don't block CI on MSYS bug

appveyor.yml, onig_sys/Cargo.toml, onig_sys/build.rs, onig_sys/src/lib.rs
Replaces `cmake` with `cc`, because [cmake is frustrating for some](https://users.rust-lang.org/t/cmake-as-a-common-external-dependency-for-rust-crates/18701). Tested on macOS 10.14, Windows 10 (MSVC), and Debian 9.4.
I've also made it possible to disable POSIX API with a Cargo feature, because this API crashes libgit2.
=> Avoid cmake dependency, workaround for crash in libgit2

Cargo.toml
I forgot to expose the posix-api feature in the parent crate
=> Ability to disable posix-api from onig crate

.travis.yml, README.md, onig/Cargo.toml, onig/src/find.rs, onig/src/lib.rs
Updates to the CI build, codebase, and documentation to explicity call out and test our minimum supported Rust version.
=> Min versions

onig_sys/Cargo.toml
bindgen is only used as library here, so its features (env_logger and clap, which are both only used with the binary) aren't useful to us.
=> Disable bindgen features

onig_sys/Cargo.toml
Some platforms require `pkgconfig` to be told to include system CFLAGS
otherwise we can't compile against the system copy of `onig`. This
updates the dependent crate to fix the issue.
Fixes: #119
=> Update `pkg-config` Crate to Fix Missing CFLAGS

onig_sys/build.rs
It appears to be a logical error to end the build if oniguruma.h was not found and thus no bindings generated. This patch fixes it.
=> onig_sys/build.rs: Error if oniguruma.h cannot be found

.appveyor.yml, .travis.yml, README.md, onig/Cargo.toml, onig/src/pattern.rs, onig_sys/Cargo.toml, onig_sys/build.rs, onig_sys/src/ffi.rs, onig_sys/src/lib.rs
This PR aims to pull together the work in #108, and #113 and provide an ergonomic solution to the problem of gnerating correct bindings for any architecture which has an LLVM version while reducing or elmininating the dependency on `bindgen` for common build and CI scenarios.
Fixes: #109, #123, #136.
=> Optional Bindgen

.appveyor.yml, .github/workflows/ci.yml, .travis.yml, README.md
Needed for the latest version of `clang-sys`. See
<https://github.com/rust-onig/rust-onig/pull/147#issuecomment-688958918>
for more information.
=> Bump MSRV to 1.40.0

onig/src/lib.rs
This means that callers who expect a `Result` value can gracefully
hadle out of bounds errors.
Fixes:  #102
=> Remove Assertions from Match and Search

onig/src/region.rs, onig/src/syntax.rs, onig/src/tree.rs
This fixes some places that might have been UB on a super-strict reading, but can't be any longer.  It changes nothing about the operation or behavior of the code—arguably it just encodes what the code should have been to begin with.
There's also a typo fix, in its own commit.
=> Ensure no UB, using `#[repr(transparent)]`

.gitignore, Vagrantfile, onig_sys/build.rs
Our fabrication of the `config.h` file left a little to be desired. On 32 bit platforms
the `st.h` file was failing to use the correct integer types for holding data values.
this then ended up in garbage reads due to bad pointer->integer->pointer casts.
Fixes #155
=> Fix for 32 bit segfaults

onig_sys/Cargo.toml
The version bump does not require any other changes, as usual for bindgen updates. A local build succeeded without issues.
=> Bump bindgen to 0.56.0

onig/src/find.rs, onig/src/region.rs, onig/src/tree.rs
Also add `Iterator::count` impls where `Iterator::size_hint` was already implemented to return `(n, Some(n))`.
I'd find these impls useful as I implement my own wrapper iterators around these iterators in a new crate I'm working on that implements a Ruby `Regexp` with multiple regex backends, one of which is `onig`.
I've done similar work in `regex`: https://github.com/rust-lang/regex/pull/734.
=> Implement FusedIterator and ExactSizeIterator where possible

.appveyor.yml, .github/workflows/ci.yml, .travis.yml, README.md, onig/Cargo.toml
Our MSRV hasn't been bumped in quite some time. We're now 15 versions
behind the current stable. Bump by 10 to try and get things building
again.
=> Bump MSRV to 1.50.0

README.md
This an extra n (LIBONING instead of LIBONIG) and caused a mistake when a copied and pasted it
=> README: Correct typo of RUSTONIG_DYNAMIC_LIBONIG

onig_sys/build.rs
This properly reruns the build if the value of $RUSTONIG_DYNAMIC_LIBONING
changes (and all the similar values)
See the cargo reference on build scripts ["change detection"](https://doc.rust-lang.org/cargo/reference/build-scripts.html#change-detection) for more details.
I have conirmed this works both on the latest stable and the MSRV (Rust 1.50)
=> onig_sys: Add cargo:rerun-if-env-changed flags

onig/Cargo.toml, onig/src/lib.rs
`onig` is the only dependency left in Artichoke's `Cargo.lock` that uses `lazy_static`. It looks like most of the ecosystem has moved to `once_cell`. `once_cell` looks to be more actively maintained and is IMO nicer to read since there are no macros. Additionally, I believe `once_cell` is a nightly Rust API so it is conceivable that once these types land in `std`, `once_cell` will simply re-export types from `std`.
See also this related change in `wasm-bindgen`:
- https://github.com/rustwasm/wasm-bindgen/pull/2962
`once_cell`'s MSRV is documented to be 1.36.0:
https://github.com/matklad/once_cell/blob/eda22cec55e9d37b16d408b7d0a5b396c7feb44c/CHANGELOG.md#151
As an aside, I noticed `onig` is using the 2015 edition. Do you have any interest in upgrading the code to 2018 edition? It's been a …
=> Replace `lazy_static` with `once_cell`

onig_sys/Cargo.toml
It solves a problem with modern clang generating invalid Idents for anonymous unions.
Fixes #173
=> Bump the bindgen version

.appveyor.yml, .github/workflows/ci.yml, .travis.yml, CHANGELOG.md, README.md, onig/Cargo.toml, onig/src/flags.rs, onig_sys/Cargo.toml
Prepare for v6.5.0 release.
As a compatibility note, bitflags v2 does not generate a `from_bits_unchecked` method. See the "major changes" section of the release notes: https://github.com/bitflags/bitflags/releases/tag/2.0.0
I consider this breakage to be minor and not worth a major version bump, but I'm happy to rev the `onig` crate to 7.0.0 if you'd prefer.
I'd appreciate getting this released. `onig` is one of the last crates in my lockfile that hasn't yet upgraded to `bitflags` v2.
=> Upgrade to bitflags v2
